services:
  api:
    build: .
    ports:
      - 8000:8000
    # volumes:  # bind mount is not working for me.
    #   - ./:/src:ro # bind mount to sync code to container - with read only -ro permission. ./ current dir on host /app= workdir in container.
    # env_file:
    #     - ./.env
    environment:
      - DATABASE_HOSTNAME=postgres
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=password123
      - DATABASE_NAME=fastapi
      - DATABASE_USERNAME=postgres
      - SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    depends_on:
      - postgres
    command: uvicorn src.app.main:app --host 0.0.0.0 --port 8000 --reload

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=fastapi
    volumes:
      - postgres-db:/var/lib/postgresql/data
    expose:
      - 5432

volumes:
  postgres-db: