name: CI Pipeline

# Trigger on push or pull request targeting the 'main' branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      # Install Poetry
      - name: Install Poetry
        run: python -m pip install --upgrade pip && pip install poetry

      # Configure Poetry to avoid creating virtual environments
      - name: Disable Poetry virtual environments
        run: poetry config virtualenvs.create false

      # Install dependencies with Poetry
      - name: Install dependencies
        run: poetry install

      # Run tests with pytest
      - name: Run tests
        run: pytest
