name: CI Pipeline

before_script:
 - python -m pip install --upgrade pip  
 - pip install poetry
 - poetry install --with development
 - source `poetry env info --path`/bin/activate

# Trigger on push or pull request targeting the 'main' branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: test with pytest
        run:  poetry run pytest
      